In [3]:
#creating an 1-d array
import numpy as np 
a = np.array([6013,2018,5060]) 
print(a)

[6013 2018 5060]


In [4]:
# more than one dimensions 
import numpy as np 
a = np.array([[6013,2018], [5060,13]]) 
print(a)

[[6013 2018]
 [5060   13]]


In [6]:
# minimum dimensions 
import numpy as np 
a = np.array([6013,13,5060,2018], ndmin = 3) 
print(a)

[[[6013   13 5060 2018]]]


In [7]:
#dtype parameter 
import numpy as np 
a = np.array([60.13,50.60,1.3], dtype = complex) 
print(a)

[60.13+0.j 50.6 +0.j  1.3 +0.j]


In [8]:
#data type
# using array-scalar type 
import numpy as np 
dt = np.dtype(np.int32) 
print(dt)

int32


In [9]:
#structured data type 
import numpy as np 
dt = np.dtype([('age',np.int8)]) 
print(dt)

[('age', 'i1')]
