In [3]:
#indexing
import numpy as np 
a = np.arange(10) 
s = slice(2,8,1) 
print(a[s])

[2 3 4 5 6 7]


In [5]:
#start,stop,step
import numpy as np 
a = np.arange(10) 
b = a[2:9:1] 
print(b)

[2 3 4 5 6 7 8]


In [7]:
# slice items starting from index 
import numpy as np 
a = np.arange(10) 
print (a[2:])

[2 3 4 5 6 7 8 9]


In [10]:
# slice items between indexes 
import numpy as np 
a = np.arange(13) 
print (a[6:13])

[ 6  7  8  9 10 11 12]


In [13]:
#slicing to an array
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)  

# slice items starting from index
print (a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
[[3 4 5]
 [4 5 6]]


In [14]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
print ('Our array is:')
print (x) 
print ('\n') 

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
   
print ('The corner elements of this array are:') 
print (y)

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The corner elements of this array are:
[[ 0  2]
 [ 9 11]]


In [15]:
#boolean array indexing
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print ('Our array is:') 
print (x)
print ('\n')  

# Now we will print the items greater than 5 
print ('The items greater than 5 are:') 
print (x[x > 5])

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The items greater than 5 are:
[ 6  7  8  9 10 11]
