In [3]:
#ordering
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4) 
   
print ('Original array is:')
print (a) 
print ('\n')  
   
print ('Transpose of the original array is:') 
b = a.T 
print (b) 
print ('\n')
   
print ('Modified array is:') 
for x in np.nditer(b): 
   print (x,)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [4]:
#nditer
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4) 

print ('Original array is:') 
print (a) 
print ('\n')  

print ('Sorted in C-style order:') 
for x in np.nditer(a, order = 'C'): 
   print (x,)  
print ('\n') 

print ('Sorted in F-style order:') 
for x in np.nditer(a, order = 'F'): 
   print (x,)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Sorted in C-style order:
0
5
10
15
20
25
30
35
40
45
50
55


Sorted in F-style order:
0
20
40
5
25
45
10
30
50
15
35
55


In [5]:
#broadcasting iteration
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4) 

print ('First array is:') 
print (a) 
print ('\n')  

print ('Second array is:') 
b = np.array([1, 2, 3, 4], dtype = int) 
print (b)  
print ('\n') 

print ('Modified array is:') 
for x,y in np.nditer([a,b]): 
   print ("%d:%d" % (x,y),)

First array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Second array is:
[1 2 3 4]


Modified array is:
0:1
5:2
10:3
15:4
20:1
25:2
30:3
35:4
40:1
45:2
50:3
55:4
