In [2]:
#amin() and amax()
import numpy as np 
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 

print ('Our array is:') 
print (a)  
print ('\n')  

print ('Applying amin() function:') 
print (np.amin(a,1)) 
print ('\n')  

print ('Applying amin() function again:') 
print (np.amin(a,0)) 
print ('\n')  

print ('Applying amax() function:') 
print (np.amax(a)) 
print ('\n' ) 

print ('Applying amax() function again:') 
print (np.amax(a, axis = 0))

Our array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Applying amin() function:
[1 4 7]


Applying amin() function again:
[1 2 3]


Applying amax() function:
9


Applying amax() function again:
[7 8 9]


In [7]:
#ptp()
import numpy as np 
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 

print ('Our array is:' )
print (a) 
print ('\n')  

print ('Applying ptp() function:') 
print (np.ptp(a)) 
print ('\n')  

print ('Applying ptp() function along axis 1:') 
print (np.ptp(a, axis = 1) )
print ('\n' )  

print ('Applying ptp() function along axis 0:')
print (np.ptp(a, axis = 0) )

Our array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Applying ptp() function:
8


Applying ptp() function along axis 1:
[2 2 2]


Applying ptp() function along axis 0:
[6 6 6]


In [8]:
#percentile
import numpy as np 
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 

print ('Our array is:') 
print (a) 
print ('\n')  

print ('Applying percentile() function:') 
print (np.percentile(a,50)) 
print ('\n')  

print ('Applying percentile() function along axis 1:') 
print (np.percentile(a,50, axis = 1)) 
print ('\n')  

print ('Applying percentile() function along axis 0:') 
print (np.percentile(a,50, axis = 0))

Our array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Applying percentile() function:
5.0


Applying percentile() function along axis 1:
[2. 5. 8.]


Applying percentile() function along axis 0:
[4. 5. 6.]


In [9]:
#median
import numpy as np 
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print ('Our array is:') 
print (a) 
print ('\n')  

print ('Applying median() function:') 
print (np.median(a) )
print ('\n')  

print ('Applying median() function along axis 0:') 
print (np.median(a, axis = 0)) 
print ('\n')  
 
print ('Applying median() function along axis 1:') 
print (np.median(a, axis = 1))

Our array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Applying median() function:
5.0


Applying median() function along axis 0:
[4. 5. 6.]


Applying median() function along axis 1:
[2. 5. 8.]


In [10]:
#mean
import numpy as np 
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 

print ('Our array is:') 
print (a) 
print ('\n')  

print ('Applying mean() function:') 
print (np.mean(a) )
print ('\n')  

print ('Applying mean() function along axis 0:') 
print (np.mean(a, axis = 0)) 
print ('\n')  

print ('Applying mean() function along axis 1:') 
print (np.mean(a, axis = 1))

Our array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Applying mean() function:
5.0


Applying mean() function along axis 0:
[4. 5. 6.]


Applying mean() function along axis 1:
[2. 5. 8.]
