In [4]:
# this resizes the ndarray 
import numpy as np 
a = np.array([[6013,13,5060],[5013,6013,2018]]) 
a.shape = (2,3) 
print(a)

[[6013   13 5060]
 [5013 6013 2018]]


In [5]:
#array of evenly spaced numbers 
import numpy as np 
a = np.arange(13) 
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [7]:
#ndmin
import numpy as np 
a = np.arange(24) 
a.ndim  

# now reshape it 
b = a.reshape(2,4,3) 
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [9]:
#itemsize
# dtype of array is int8 (1 byte) 
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.int8) 
print (x.itemsize)

1


In [10]:
#flags
import numpy as np 
x = np.array([1,2,3,4,5]) 
print (x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

