In [1]:
# convert list to ndarray 
import numpy as np 
x = [6013,2018,5060] 
a = np.asarray(x) 
print( a)

[6013 2018 5060]


In [3]:
# dtype is set 
import numpy as np 

x = [6013,2018,5060]
a = np.asarray(x, dtype = float) 
print (a)

[6013. 2018. 5060.]


In [5]:
# ndarray from tuple 
import numpy as np 

x = (6013,5060,2018) 
a = np.asarray(x) 
print(a)

[6013 5060 2018]


In [6]:
# ndarray from list of tuples 
import numpy as np 

x = [(13,6013,2018),(5060,6013)] 
a = np.asarray(x) 
print(a)

[(13, 6013, 2018) (5060, 6013)]


In [7]:
# obtain iterator object from list 
import numpy as np 
list = range(5) 
it = iter(list)  
# use iterator to create ndarray 
x = np.fromiter(it, dtype = float) 
print(x)

[0. 1. 2. 3. 4.]
